name: Integration Test

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Docker
        uses: docker-practice/actions-setup-docker@master
      - name: Install Protoc
        uses: arduino/setup-protoc@v1
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Copy integration config
        run: cp .env.test .env
      - name: Run Raccoon
        run: make docker-run
      - run: make install-protoc && make generate-proto
      - name: Invoking go test
        run: INTEGTEST_BOOTSTRAP_SERVER=localhost:9094 INTEGTEST_HOST=ws://localhost:8080 INTEGTEST_TOPIC_FORMAT="clickstream-%s-log" go test ./integration -v
